$defs:
  env:
    type: object
    propertyNames: { type: string }
    additionalProperties: { type: string }

# suite
type: object
additionalProperties: false
required: []
properties:
  env:  { "$ref": "#/$defs/env" }
  name: { type: string }
  tests:
    type: object
    additionalProperties:

      # test
      type: object
      additionalProperties: false
      required: []
      properties:
        env:  { "$ref": "#/$defs/env" }
        name: { type: string }
        steps:
          type: array
          items:

            # step
            type: object
            additionalProperties: false
            required: [ exec, run ]
            properties:
              env:  { "$ref": "#/$defs/env" }
              exec: { type: string }
              name: { type: string }
              run:  { type: string }
