#!/usr/bin/env bash

TARGET_NAME=$(basename "${0}")
TARGET_DIR=$(readlink -f $(dirname "${0}"))
ROOT_DIR=$(dirname $(readlink -f "${0}"))/..

NBB=$(which 2>/dev/null ${ROOT_DIR}/node_modules/.bin/nbb | head -n1)

die() { echo >&2 "${*}"; exit 1; }

[ -e "${NBB}" ] || die "Missing ${NBB}. Maybe run 'npm install' in ${ROOT_DIR}?"

DCTEST_SCHEMA="${DCTEST_SCHEMA:-${ROOT_DIR}/schema.yaml}" \
  NODE_PATH="${ROOT_DIR}/node_modules" exec ${NBB} \
  -cp "${ROOT_DIR}/src:${ROOT_DIR}/test:${ROOT_DIR}/node_modules/@lonocloud/cljs-utils/src" \
  "${TARGET_DIR}/${TARGET_NAME}.cljs" "${@}"
