#!/usr/bin/env bash

TARGET_NAME=$(basename "${0}")
TARGET_DIR=$(readlink -f $(dirname "${0}"))
ROOT_DIR=$(dirname $(readlink -f "${0}"))/..

NBB=$(which 2>/dev/null ${ROOT_DIR}/node_modules/.bin/nbb | head -n1)

die() { echo >&2 "${*}"; exit 1; }

[ -e "${NBB}" ] || die "Missing ${NBB}. Maybe run 'npm install' in ${ROOT_DIR}?"

NODE_PATH="${ROOT_DIR}/node_modules" exec ${NBB} -cp "${ROOT_DIR}/src" "${TARGET_DIR}/${TARGET_NAME}.cljs" "${@}"
