name: Push

on:
  push: {}
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch: {}

jobs:

  test-node:
    name: Run Tests+Examples (Node ${{ matrix.node_version }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node_version: [ '16.x', '18.x', '20.x', '22.x' ]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with: { submodules: 'recursive', fetch-depth: 0 }

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node_version }}
      - name: Install NPM
        run: npm install

      - name: Run Tests
        run: ./test/runtests

      - name: Run Examples
        run: ./test/runexamples

  test-docker:
    name: Run Examples (Docker)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with: { submodules: 'recursive', fetch-depth: 0 }

      - name: Build Image
        run: |
          docker build -t dctest .

      - name: Install NPM (for schema validation)
        run: npm install

      - name: Run Examples
        env:
          DCTEST_IMAGE: dctest
        run: ./test/runexamples
