name: Push

on:
  push: {}
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch: {}

jobs:

  cljs-tests:
    name: Run CLJS tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with: { submodules: 'recursive', fetch-depth: 0 }

      - name: Install NPM
        run: npm install

      - name: Run Tests
        run: ./test/runtests

  test-examples-node:
    name: Test Examples (Node)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with: { submodules: 'recursive', fetch-depth: 0 }

      - name: Install NPM
        run: npm install

      - name: Run Examples
        run: ./test/runexamples

  test-examples:
    name: Test Examples (Docker)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with: { submodules: 'recursive', fetch-depth: 0 }

      - name: Build Image
        run: |
          docker build -t dctest .

      - name: Install NPM (for schema validation)
        run: npm install

      - name: Run Examples
        env:
          DCTEST_IMAGE: dctest
        run: ./test/runexamples
